# Generated by Django 5.2.5 on 2025-10-22 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bemjs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('quantity', models.TextField(default='notitle')),
                ('emojiname', models.TextField(default='notitle')),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='c', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cattendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no', max_length=100)),
                ('school', models.CharField(default='no', max_length=100)),
                ('klass', models.CharField(default='no', max_length=100)),
                ('day', models.CharField(default='yes', max_length=100)),
                ('adm_no', models.CharField(default='no', max_length=100)),
                ('state', models.CharField(default='no', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='checkoff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checkIn', models.CharField(blank=True, default='notyet', max_length=100)),
                ('checkout', models.CharField(blank=True, default='notyet', max_length=100)),
                ('driver', models.CharField(blank=True, default='dere', max_length=100)),
                ('useryou', models.CharField(blank=True, default='child', max_length=100)),
                ('datetime', models.CharField(blank=True, default='time', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('menu', models.CharField(default='menu', max_length=100)),
                ('session', models.CharField(default='yes', max_length=100)),
                ('school', models.CharField(default='school', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Classx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('menu', models.CharField(default='menu', max_length=100)),
                ('school', models.CharField(default='school', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='event1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('date', models.TextField(default='notitle')),
                ('skills', models.TextField(default='notitle')),
                ('title', models.TextField(default='notitle')),
                ('location', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='game1', max_length=100)),
                ('price', models.CharField(default='game1', max_length=100)),
                ('points', models.CharField(default='1', max_length=100)),
                ('save1', models.CharField(default='1', max_length=100)),
                ('count', models.CharField(default='1', max_length=100)),
                ('image_url', models.TextField(default='notitle')),
            ],
        ),
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no', max_length=100)),
                ('school', models.CharField(default='no', max_length=100)),
                ('klass', models.CharField(default='no', max_length=100)),
                ('session', models.CharField(default='yes', max_length=100)),
                ('adm_no', models.CharField(default='no', max_length=100)),
                ('subject', models.CharField(default='no', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daydate', models.CharField(default='prontoday', max_length=100)),
                ('time', models.CharField(default='prontotrip', max_length=100)),
                ('dist', models.CharField(default='prontoccurence', max_length=100)),
                ('student_number', models.CharField(default='dere', max_length=100)),
                ('est_fuel', models.CharField(default='sess', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hmss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='headline', max_length=100)),
                ('topic', models.CharField(default='samdhing real', max_length=100)),
                ('mclass', models.CharField(default='samdhing real', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='hmss2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no', max_length=100)),
                ('date', models.CharField(default='no', max_length=100)),
                ('lass', models.CharField(default='no', max_length=100)),
                ('school', models.CharField(default='no', max_length=100)),
                ('subject', models.CharField(default='no', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whoiswho', models.CharField(default='whoiswho', max_length=1000)),
                ('to', models.CharField(default='noo', max_length=1000)),
                ('tag', models.CharField(default='nooo', max_length=1000)),
                ('location', models.CharField(default='', max_length=1000)),
                ('writer', models.CharField(blank=True, default='anonymous', max_length=1000)),
                ('mation', models.CharField(default='', max_length=10000)),
                ('title', models.CharField(default='notitle', max_length=1000)),
                ('image1', models.TextField(default='notitle')),
                ('image2', models.TextField(default='notitle')),
                ('image3', models.TextField(default='notitle')),
                ('image', models.TextField(default='notitle')),
                ('delete', models.CharField(default='no', max_length=10)),
                ('date', models.CharField(default='no date', max_length=1000)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='matukio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('usertype', models.TextField(default='notitle')),
                ('datetime', models.TextField(default='notitle')),
                ('sessiontime', models.TextField(default='notitle')),
                ('event', models.TextField(default='notitle')),
                ('device', models.TextField(default='notitle')),
                ('geolocation', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day', models.CharField(default='todaay', max_length=255)),
                ('start_time', models.CharField(default='timezone.now', max_length=255)),
                ('end_time', models.CharField(default='timezone.now', max_length=255)),
                ('color', models.CharField(default='#FF5722', max_length=255)),
                ('is_all_day', models.CharField(default='False', max_length=255)),
                ('room', models.CharField(default='notspecified', max_length=255)),
                ('username', models.CharField(max_length=150)),
                ('prioritylevel', models.CharField(default='normal', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='messageswick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='game1', max_length=100)),
                ('sender', models.TextField(default='notitle')),
                ('message_me', models.TextField(default='notitle')),
                ('receiver', models.CharField(default='game1', max_length=100)),
                ('time', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='mpatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(default='game1', max_length=100)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('fl', models.TextField(default='notitle')),
                ('dob', models.TextField(default='notitle')),
                ('gender', models.TextField(default='notitle')),
                ('location', models.TextField(default='notitle')),
                ('county', models.TextField(default='notitle')),
                ('country', models.TextField(default='notitle')),
                ('postalcode', models.TextField(default='notitle')),
                ('phonenumber', models.TextField(default='notitle')),
                ('emcontact', models.TextField(default='notitle')),
                ('emcontact2', models.TextField(default='notitle')),
                ('bloodtype', models.TextField(default='notitle')),
                ('allergies', models.TextField(default='notitle')),
                ('medhistory', models.TextField(default='notitle')),
            ],
        ),
        migrations.CreateModel(
            name='notef',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titles', models.CharField(blank=True, default='titles', max_length=100)),
                ('state', models.CharField(blank=True, default='offline', max_length=100)),
                ('numbx', models.CharField(blank=True, default='old', max_length=100)),
                ('useryou', models.CharField(blank=True, default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Online',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username1', models.CharField(default='none', max_length=1000)),
                ('image', models.CharField(default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(default='game1', max_length=100)),
                ('owner', models.TextField(default='notitle')),
                ('food', models.TextField(default='notitle')),
                ('restaurantx', models.CharField(default='game1', max_length=100)),
                ('time', models.CharField(default='game1', max_length=100)),
                ('totalprice', models.CharField(default='game1', max_length=100)),
                ('ordertype', models.CharField(default='game1', max_length=100)),
                ('orderlocation', models.CharField(default='game1', max_length=100)),
                ('ordertrak', models.CharField(default='game1', max_length=100)),
                ('ordertime', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orderconf',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Mpesacode', models.CharField(default='game1', max_length=100)),
                ('owner', models.TextField(default='notitle')),
                ('location', models.CharField(default='game1', max_length=100)),
                ('time', models.CharField(default='game1', max_length=100)),
                ('totalprice', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profpic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username1', models.CharField(default='none', max_length=1000)),
                ('image', models.CharField(default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sbus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameq', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('place', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('school', models.CharField(default='samdhing real', max_length=100)),
                ('commute', models.CharField(default='off', max_length=100)),
                ('cordinates', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(default='pronto', max_length=100)),
                ('day', models.CharField(default='prontoday', max_length=100)),
                ('trip', models.CharField(default='prontotrip', max_length=100)),
                ('occurence', models.CharField(default='prontoccurence', max_length=100)),
                ('driver', models.CharField(default='dere', max_length=100)),
                ('session', models.CharField(default='sess', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schoolID', models.CharField(default='schid', max_length=1000)),
                ('school', models.CharField(default='Sch', max_length=1000)),
                ('childname', models.CharField(default='childname', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='School1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='he', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username1', models.CharField(default='none', max_length=1000)),
                ('image', models.CharField(default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no', max_length=100)),
                ('school', models.CharField(default='not done', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='stagemine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
                ('place', models.CharField(blank=True, default='', max_length=1000)),
                ('coordinates', models.CharField(default='', max_length=1000)),
                ('school', models.CharField(default='samdhing real', max_length=100)),
                ('usernamemi', models.CharField(default='nouser', max_length=1000)),
                ('curbus', models.CharField(default='xon', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('School', models.TextField(default='School')),
                ('Class', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('profpic', models.CharField(default='jello', max_length=10000, null=True)),
                ('adm_no', models.CharField(blank=True, default='', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['adm_no'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('school', models.CharField(default='samdhing real', max_length=100)),
                ('Class', models.CharField(default='samng real', max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('School', models.CharField(blank=True, default='', max_length=100)),
                ('adm_no', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='tranzoia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sc', models.CharField(blank=True, default='', max_length=100)),
                ('bi', models.CharField(blank=True, default='', max_length=100)),
                ('school', models.CharField(default='samdhing real', max_length=100)),
                ('userN', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='unfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('likes', models.TextField(default='notitle')),
                ('skills', models.TextField(default='notitle')),
                ('location', models.CharField(default='game1', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(default='1', max_length=100)),
                ('food', models.CharField(default='1', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Verified',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username1', models.CharField(default='none', max_length=1000)),
                ('image', models.CharField(default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Verified2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username1', models.CharField(default='none', max_length=1000)),
                ('image', models.CharField(default='', max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='work1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title2', models.CharField(default='event title', max_length=100)),
                ('username', models.CharField(default='game1', max_length=100)),
                ('salary', models.TextField(default='notitle')),
                ('skills', models.TextField(default='notitle')),
                ('title', models.CharField(default='game1', max_length=100)),
                ('location', models.CharField(default='game1', max_length=100)),
                ('time', models.CharField(default='time', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ategoryx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='x', max_length=10000)),
                ('image', models.CharField(default='1', max_length=10000)),
                ('caption', models.CharField(default='x', max_length=10000)),
                ('food', models.ManyToManyField(to='cloud2.food')),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no homework', max_length=100)),
                ('deadline', models.CharField(default='', max_length=100)),
                ('Class', models.ManyToManyField(blank=True, to='cloud2.class')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ManyToManyField(to='cloud2.category')),
            ],
        ),
        migrations.CreateModel(
            name='Menux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ManyToManyField(blank=True, to='cloud2.ategoryx')),
            ],
        ),
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(default='game1', max_length=100)),
                ('city', models.CharField(default='game1', max_length=100)),
                ('image_of_restaurant', models.TextField(default='notitle')),
                ('menu', models.ManyToManyField(blank=True, to='cloud2.menux')),
                ('orders', models.ManyToManyField(blank=True, to='cloud2.order2')),
                ('username', models.ForeignKey(default='game1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='he', max_length=100)),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='food',
            field=models.ManyToManyField(to='cloud2.subject'),
        ),
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='x', max_length=10000)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('menu', models.ManyToManyField(blank=True, to='cloud2.menux')),
            ],
        ),
    ]
